### ISSUE TITLE
Bug við 240397 22x

### ISSUE THREAD

**Issue by mimiqkz** [HermannBjorgvin/Kennitala#13]
Veit ekki afhverju en alltaf þegar ég slæ inn `240397 22x` fær ég alltaf `isPerson(...)` sem `true`.

**Comment by HermannBjorgvin** [comment]
Góðan dag, ertu með kóðadæmi fyrir mig?

Ef ég prófa þennan streng í NPM runkit þá skilar `kennitala.isPerson("240397 22x")`  `false`.

https://npm.runkit.com/kennitala
```js
var kennitala = require("kennitala")

kennitala.isPerson("240397 22x");
```

**Comment by mimiqkz** [comment]
Já, það er bara
```
var kennitala = require("kennitala")

kennitala.isPerson("240397222"); 
```

eða 

```
var kennitala = require("kennitala")

kennitala.isPerson("240397223"); 
```

x þarna sem ég skrifaði er bara allar tölur sem eru 0 til 9

**Comment by mimiqkz** [comment]
version sem ég er að nota er `1.2.4`

**Comment by HermannBjorgvin** [comment]
Mér sýnist þessi lína vera að valda þessu. Þegar kennitala er nákvæmlega 9 tölu löng þá gerir pakkinn ráð fyrir innsláttarvillu og bætir við "0" fyrir framan.

https://github.com/HermannBjorgvin/Kennitala/blob/4f5cfeabf6d173da809c7f48411ac2ca7bb5350e/kennitala.js#L239

Kannski er þetta ekki rétt nálgun fyrst fólk getur lent í svona villum við innslátt

**Comment by HermannBjorgvin** [comment]
Uppfæri bráðlega og set kröfu um 10 stafa kennitölur

**Comment by HermannBjorgvin** [comment]
Closed in latest pull request
