### ISSUE TITLE
isPerson does not look at the last digit

### ISSUE THREAD

**Issue by unnsteinngardars** [HermannBjorgvin/Kennitala#20]
The last digit is the century, so I would think that future proofing for all upcoming centuries is not correct, that is, I would expect the last digit for a person to only be valid if it is 0 or 9. What do you think about this @HermannBjorgvin ?

**Comment by HermannBjorgvin** [comment]
@unnsteinngardars I suppose it's ok to have a breaking change once per century, so this validation would be good for about 80 years.

We can add this to the V2 refactor discussion, I don't see a reason not to include this in the next version.

https://github.com/HermannBjorgvin/Kennitala/discussions/19
